- name: Retrieve all available Openstack hypervisors
  os_hypervisor_facts:
    enabled: True
    active: True
    validate_certs: no

- name: Create new instance with prometheus, alert manager and alerta
  register: "os_hosts"
  os_server:
    state: present
    timeout: 200
    name: "{{ instance_name }}-{{ item }}"
    cloud: "{{ cloud }}"
    image: "{{ image_id }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor_id }}"
    security_groups: "{{ security_groups }}"
    # TODO (msenin): disable floating ip
    auto_ip: "{{ assign_floating_ip }}"
    # floating_ip_pools: "{{ floating_ip_pools if assign_floating_ip == true else omit }}"
    nics: [ net-id: "{{ net_id }}" ]
    validate_certs: no
    userdata: "{{ cloudinit }}"
    meta:
      hostname: "{{ instance_name }}"
      group: "{{ group }}"
  loop: "{{ range(0, instance_count)|list }}"

- set_fact:
    master_instance_ip: "{{ groups['master'][0] }}"

- name: Add hosts to inventory
  add_host:
    name: "{{ item['server']['private_v4'] }}"
    ansible_user: "{{ instance_manage_user }}"
    groups: "{{ group }}"
    instance_name: "{{ item['server']['name'] }}"
    ansible_host: "{{ item['server']['private_v4'] }}"
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -i {{ ansible_ssh_private_key_file }} -W %h:%p -q {{ instance_manage_user }}@{{ master_instance_ip }}"'
  loop: "{{ os_hosts.results }}"

- name: Wait for system to become reachable
  wait_for_connection:
    timeout: "{{ waiter_timeout }}"
