- name: Get docker sign key
  apt_key:
    url: "{{ docker_sign_key_url }}"
    state: present
  # TODO (msenin): https://github.com/ansible/ansible/issues/31691
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

- name: Add docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_repo_url }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes

- name: Install docker-ce package
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Install python3-pip package
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Pip force upgrade
  pip: 
    name: pip
    extra_args: --upgrade
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

- name: Install docker compose
  pip:
    name: docker-compose
    #state: forcereinstall
  # TODO (msenin): move to root main.yaml
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
